volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: wtfucka/foodgram_backend
    restart: always
    volumes:
      - static_value:/app/foodgram_static/
      - media_value:/app/foodgram_media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: wtfucka/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  gateway:
    image: wtfucka/foodgram_gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/foodgram_static/
      - media_value:/var/html/foodgram_media/
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
