TAG_SLUG_MAX_LENGTH = 200
TAG_NAME_MAX_LENGTH = 200
TAG_COLOR_MAX_LENGTH = 7

INGREDIENT_AMOUNT_MIN_VALUE = 1
INGREDIENT_AMOUNT_MAX_VALUE = 9999
INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_UNIT_MAX_LENGTH = 200

RECIPE_NAME_MAX_LENGTH = 200
RECIPE_IMAGE_MAX_VALUE = 5
RECIPE_COOKING_TIME_MIN_VALUE = 1
RECIPE_COOKING_TIME_MAX_VALUE = 9999

IMAGE_EXTENSION_TYPE = -1
